substitutions:
  name: "media-player"
  friendly_name: "Media Player"
  media_player: ""
  display_rotation: "180"
  touch_swap_xy: "false"
  touch_mirror_x: "true"
  touch_mirror_y: "true"

esphome:
  name_add_mac_suffix: true
  project:
    name: jtenniswood.media-player
    version: "1.0"

packages:
  music_dashboard: !include ../guition-esp32-s3-4848s040/packages.yaml

wifi:
  ap:

captive_portal:
